# Generated by Django 3.2.7 on 2021-10-07 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 10, 7, 11, 17, 44, 616447, tzinfo=utc), upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='course',
            field=models.CharField(default='', max_length=60),
        ),
    ]
