# Generated by Django 3.2.8 on 2021-10-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='course',
        ),
        migrations.RemoveField(
            model_name='college',
            name='image',
        ),
    ]
