# Generated by Django 3.2.8 on 2021-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211021_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
