# Generated by Django 3.2.6 on 2021-08-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_ceo', models.CharField(max_length=280)),
                ('company_startup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_code', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=300)),
                ('car_price', models.IntegerField()),
                ('car_color', models.CharField(max_length=200)),
                ('car_topspeed', models.FloatField(default=0)),
                ('car_modelyear', models.IntegerField()),
                ('car_milage', models.FloatField()),
                ('car_company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.company')),
            ],
        ),
    ]
