# Generated by Django 3.2.6 on 2021-08-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.location'),
        ),
    ]
