# Generated by Django 3.2.6 on 2021-08-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_company_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='company_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.location'),
        ),
    ]
