# Generated by Django 3.2.6 on 2021-08-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_car_car_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restrurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=200)),
                ('rest_dish', models.CharField(max_length=600)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carapp.place')),
            ],
        ),
    ]
