# Generated by Django 3.2.4 on 2021-11-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_place_restrurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
