# Generated by Django 3.2.6 on 2021-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
