# Generated by Django 3.2.6 on 2021-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0003_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalmoney',
            field=models.IntegerField(default=0),
        ),
    ]
