# Generated by Django 3.2.6 on 2021-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0004_profile_totalmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totalmoney',
        ),
    ]
