# Generated by Django 3.2.7 on 2021-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0006_forgetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpassword',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='forgetpassword',
            name='url_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
