# Generated by Django 3.2.7 on 2021-09-23 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappp', '0007_auto_20210923_0710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgetPassword',
            new_name='ForgetPassword2',
        ),
    ]
